version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD} 
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5435:5432
    env_file:
      - .env

  app:
    build: .
    ports:
      - ${PORT}:3000
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    env_file:
      - .env

volumes:
  postgres: